<!DOCTYPE html>
  <head>
    <title>Learning PouchDB</title>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0">

    <link rel="stylesheet" type="text/css" href="/dist/styles-{{package.version}}.css" />
    <link rel="icon" href="/images/favicon.png">

    {% block head %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}

    <script type="text/javascript" src="/dist/scripts-{{package.version}}.js"></script>
  </body>
</html>
